### PR TITLE
fix: scale custom on mobile

### LINKED ISSUE #13322: Scale custom not working on mobile
### Bug Description

The scale custom feature implemented in #13045 doesn't work correctly on mobile.

Specifically, the functionality is there but the controls to activated are not displayed.

I already have a fix that I will PR ASAP.

### How to Reproduce

Just opening the Display Settings menu and selecting "Scale custom". Tested on Android, I believe it's broken on iOS as well.

### Expected Behavior

The "Custom" part of "Scale Custom" should be customizable! 😅 

### Operating system(s) on local (controlling) side and remote (controlled) side

Android

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.4.3

### Screenshots

Image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by deblasis**
This PR simply fixes #13322 by adding the missing componentry for mobile.

https://github.com/user-attachments/assets/53a0bf3d-3311-4b34-9a7b-4f0794be11d7

### CODE REVIEW

**Comment by deblasis** [comment]
@fufesou; I suppose we should also add the revert for commit 265d08f  here?

**Comment by rustdesk** [comment]
> @fufesou; I suppose we should also add the revert for commit [265d08f](https://github.com/rustdesk/rustdesk/commit/265d08fc3b72c6d61f0840f0d61d13fe248230fe) here?

Yes, please revert [flutter/lib/common/widgets/toolbar.dart](https://github.com/rustdesk/rustdesk/commit/265d08fc3b72c6d61f0840f0d61d13fe248230fe#diff-7b864e44a5d8f717b1a281562e9d8b624314c09a1402cf0f5a1a74aaddcbeba4) only.

**Comment by fufesou** [comment]
@deblasis Hi, this PR works fine on Android.

But most of the code in `flutter/lib/mobile/widgets/custom_scale_widget.dart` is duplicated from the code in `flutter/lib/desktop/widgets/remote_toolbar.dart`.

Is it possible to extract the common functions or widgets?

**Comment by deblasis** [comment]
Done and tested on android and macOS

File: flutter/lib/common/widgets/custom_scale_mixin.dart [hunk 1]
```diff
@@ -0,0 +1,157 @@
...
+import 'package:flutter_hbb/utils/scale.dart';
+import 'package:flutter_hbb/common.dart';
+
+/// Mixin providing shared custom scale control logic for both mobile and desktop widgets.
+/// Implementations must provide [ffi] and [onScaleChanged] getters.
+///
+/// Note: Members are intentionally not private (no underscore) to allow access from
+/// implementing classes in different libraries. Implementing classes should treat
+/// these as protected members.
+mixin CustomScaleControlsMixin<T extends StatefulWidget> on State<T> {
```
[the remark this answers is not in the document]
Comment (deblasis) [reply flutter/lib/common/widgets/custom_scale_mixin.dart]: Refactored to use abstract class instead

**Comment by fufesou** [comment]
Hi, I can't drag the slider (scale) on Android now.
Maybe this suggestion is wrong. https://github.com/rustdesk/rustdesk/pull/13324#discussion_r2472876693


The following code works fine to me, the dialog does not dismiss.
```dart
GestureDetector(
  child: MobileCustomScaleControls(ffi: gFFI),
),
```

`onTap: () {}, // Absorb tap events to prevent dialog dismiss` is it needed?

**Comment by deblasis** [comment]
Hi @fufesou , 

> Hi, I can't drag the slider (scale) on Android now. Maybe this suggestion is wrong. [#13324 (comment)](https://github.com/rustdesk/rustdesk/pull/13324#discussion_r2472876693)

sorry about that, I made 2 mistakes: 
- I trusted CoPilot
- I tested the wrong branch (the one with some extra code to run the android emulator on my machine)


> The following code works fine to me, the dialog does not dismiss.
> 
> ```dart
> GestureDetector(
>   child: MobileCustomScaleControls(ffi: gFFI),
> ),
> ```
> 
> `onTap: () {}, // Absorb tap events to prevent dialog dismiss` is it needed?

I did some research and I think you are right, onTap is not necessary but I think that 

opaque → const [HitTestBehavior](https://api.flutter.dev/flutter/rendering/HitTestBehavior.html)
Opaque targets can be hit by hit tests, causing them to both receive events within their bounds and prevent targets visually behind them from also receiving events.

Might be necessary here. Am I missing something?

Updating with your suggestion btw, I am just curious 😄

File: flutter/lib/mobile/pages/remote_page.dart [hunk 2]
```diff
@@ -1201,6 +1202,12 @@ void showOptions(
                     if (v != null) viewStyle.value = v;
                   }
                 : null)),
+      // Show custom scale controls when custom view style is selected
+      Obx(() => viewStyle.value == kRemoteViewStyleCustom
+          ? GestureDetector(
```
Comment (fufesou) [inline flutter/lib/mobile/pages/remote_page.dart]: Maybe single `GestureDetector` is the same to `Container`.
You can just simplify changing 

```dart
          ? GestureDetector(
              child: MobileCustomScaleControls(ffi: gFFI),
            )
``` 

to 

```dart
          ? MobileCustomScaleControls(ffi: gFFI)
```

**Review by fufesou — CHANGES_REQUESTED** [review]

File: flutter/lib/mobile/pages/remote_page.dart (hunk 2 above)
Comment (deblasis) [reply flutter/lib/mobile/pages/remote_page.dart]: Makes sense, done

**Review by fufesou — APPROVED** [review]
