### PR TITLE
Fix remote home button in file transfer

### LINKED ISSUE #3508: File Manager. Dialog Confirm overwrite does not behave as expected.
### Bug Description

The confirmation dialog for overwriting an existing file does not work properly.

1. sometimes it does not appear at all, files are silently skipped.
2. sometimes it appears only in one direction. Forgot which one it was, can't reproduce it at the moment because of "1."
3. when selecting multiple files, e.g. "select all", many dialogs are opened, but not as many as files were selected.
4. "Do this for all conflicts" does not work, behaves the same as "close this dialog".

### How to Reproduce

Open File Manger, select more than 5 files and click "receive" or "send", repeat it, play around.

### Expected Behavior

1. Dialog always displayed when a file already exists in goal.
2. "Do this for all conflicts" do so.

### Operating system(s) on local side and remote side

Linux > Android

### RustDesk Version(s) on local side and remote side

source

### Screenshots

Selected files are more than 5.

confirm-overwrite-buggy

Dialogs disappear after a few clicks, but selected files are more.

Wanted to create a new video, but can't reproduce this anymore, instead i experienced that the files are skipped silently.

confirm-overwrite-skipped-automaticlly

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by beelchester**
fixes https://github.com/rustdesk/rustdesk/issues/3508#issuecomment-1758746599
The original issue of #3508 has been already fixed (confirmed by OP and me).

~~Storing and fetching remote home directory for remote home button.~~
Setting the directory as empty is opening home directory.
Rest implementation is unchanged. Local remote home button is working the same as before.

https://github.com/rustdesk/rustdesk/assets/73148455/15103ad5-a035-4ead-9773-bb163c2ce3db

### CODE REVIEW

File: flutter/lib/models/file_model.dart [hunk 1]
```diff
@@ -423,6 +429,14 @@ class FileController {
         }
       } else if (options.value.home.isEmpty) {
         options.value.home = fd.path;
+
+        final homeDir = ( await bind.sessionGetPeerOption(
+          sessionId: sessionId, name: "remote_home_dir"));
+
+        if (homeDir.isEmpty){
```
Comment (rustdesk) [inline flutter/lib/models/file_model.dart]: I guess you should run format.

File: flutter/lib/models/file_model.dart [hunk 2]
```diff
@@ -423,6 +429,14 @@ class FileController {
...
+          bind.sessionPeerOption(
+            sessionId: sessionId, name: "remote_home_dir", value: fd.path);
+        }
```
Comment (rustdesk) [inline flutter/lib/models/file_model.dart]: Do we really need store it as peer option? it will write disk and pollute peer options.

> I could not find any direct implementation for the remote home directory yet but since the home path is correct in the first connection we can just store it according to the session ID and fetch it whenever needed.

Comment (beelchester) [reply flutter/lib/models/file_model.dart]: Ok, I will try to find a better way to get home directory. Or do you mean to store it somewhere else?

**Comment by sahilyeole** [comment]
New changes:

- Removed the need for storing.
- Setting the directory as empty is opening home directory.
- Tested win, android, linux as remote side. Remote button is working the same as the video above.
